### PR TITLE
[ADD] allow merging via sha1 hash

### PR DESCRIPTION
**Pull request by hbrunn**
for the same reasons as for addons, tagging is not always feasible, so we should allow pinning to commit hashes

PS: The message `fetch_remote_sha` is a bit annoying, would an option in the lines of `warn_git_sha1_pinning = {True,False}` with default to `True` be accepted if I PR it?

### CODE REVIEW

**Comment by gracinet** [comment]
Hi Holger, I have nothing in principle against opting out of the message. I encourage even you to advertise within the message how to get rid of it.

So far almost everybody reacted along the lines of « we don't have a choice » or « we don't force push » anyway.

I'll be on leave for 2 weeks starting right now.
Ccing @petrus-v , who watches these more closely that I do these days anyway

**Comment by gracinet** [comment]
red travis is due to pep8 rules that also complain on master (being relatively recently enforced and all that). Will have to fix them.

**Comment by gracinet** [comment]
Speaking of flake8, there's PR #70

**Comment by hbrunn** [comment]
@petrus-v @gracinet merged travis fixes, now it should come up green

**Comment by petrus-v** [comment]
@hbrunn 

Thanks for this PR and the merge!

Can I ask you to write a unit test or improve the existing ones to cover this use case?

https://github.com/anybox/anybox.recipe.odoo/blob/master/anybox/recipe/odoo/vcs/tests/test_git.py#L495

**Comment by hbrunn** [comment]
@petrus-v of course, done

**Comment by petrus-v** [comment]
@hbrunn,

Thanks for this PR! LGTM

**Comment by petrus-v** [comment]
@hbrunn 

I've add the line in change log and add you as anybox.recipe.odoo contributor ;-)
https://github.com/anybox/anybox.recipe.odoo/commit/b80c95a7770c2902d6aaf2305c68036dd7715862

Regards

**Comment by hbrunn** [comment]
yay, thanks for the honors!

**Pull request merged**
