### PR TITLE
Responsive design documentation

### PR DESCRIPTION
**Pull request by petrus-v**
New theme for a responsive documentation using *sphinx_bootstrap_theme*.

### CODE REVIEW

**Comment by petrus-v** [comment]
When #59 will be merged, I'll rebase this PR to test building doc on travis adding sphinx_bootstrap_theme extra dependency

**Comment by lmignon** [comment]
:+1:  Nice! (build + result tested)

**Comment by petrus-v** [comment]
As #59 was merged, I rebase branch! Travis build it correctly!

I have to check anybox buildbot requirement before merging this branch.

**Comment by lmignon** [comment]
@petrus-v Is this one ready to merge?

**Comment by petrus-v** [comment]
@lmignon,

Thanks for your interest. No it's not ready, I haven't check if I need to do something on buildbot.anbyox.fr to build documentation properly with `sphinx_bootstrap_theme`.

I'll let you know when it'll be done.

**Comment by petrus-v** [comment]
@gracinet, @ccomb,

It's probably not the good place to talk about that! what's plan about CI on buildbot.anybox.fr as long we are now using Travis?

About the documentation, I've test a way to do using ``gh-pages`` branch, then github allow you to visit the documentation on : http://petrus-v.github.io/anybox.recipe.odoo/ (BTW, you can now easily review this PR :D )

So It could be Travis that commit on ``gh-pages`` branch which should be something like I've done here:
```
cd doc
rm -rf sphinx_build/
~/tmp/recipe-env/bin/sphinx-build . sphinx_build/
cd sphinx_build
# Disable Jekyll to avoid 404 error for files in ``_static`` directory
touch .nojekyll
git add .
git commit -m "Deploy to GitHub Pages"
# do not keep history
git push --force --quiet git@github.com:petrus-v/anybox.recipe.odoo.git master:gh-pages
```

According this gist we should able to let travis commit in the repo: https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

We will have to define what's happen on PR and building different branches but before go in deep, I would like to know what you think about?

**Comment by lmignon** [comment]
@petrus-v Here it-is the way we publish the documentation for some Odoo module with travis
https://github.com/OCA/geospatial/blob/8.0/.travis_push_doc

```bash
#!/bin/bash

set -o errexit -o nounset
if [ $TRAVIS_BRANCH = "8.0" ] && [ $TRAVIS_PULL_REQUEST = false ]; then
    cd ${TRAVIS_BUILD_DIR}
    rev=$(git rev-parse --short HEAD)

    cd ${HOME}/build_doc
    git init
    git config user.name "Nicolas Bessi"
    git config user.email "nicolas.bessi@camptocamp.com"
    git remote add upstream https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
    git fetch upstream
    git reset upstream/gh-pages

    # echo "domain to do"  > CNAME
    touch .nojekyll

    touch .
    git add -A .
    git commit -m"rebuild pages at ${rev}"

    git push -q upstream HEAD:gh-pages
fi
```

**Comment by gracinet** [comment]
Thanks, this looks more from the 2010s :-)
Merged, although I'd prefer the foreground color in navbar to be black rather than this white that I personally don't find very readable (don't have the time right now to really dig into how to recompile bootswatch with a change in less variables).

And the doc's been built by Anybox's [buildbot](https://buildbot.anybox.fr/#/builders/14/builds/28)

**Comment by gracinet** [comment]
Forgot link for the [built doc](http://docs.anybox.fr/anybox.recipe.odoo/current/)

**Pull request merged**
