### PR TITLE
Relocation

### PR DESCRIPTION
**Pull request by StefanRijnhart**
This is a continuation of the work of @jbaudoux on relocatable buildouts. This version supports relative addons paths in Odoo for all the scripts.

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
This is basically a port of https://code.launchpad.net/~jbaudoux/anybox.recipe.openerp/1.8.5_relative_paths_jailroot/+merge/237238. I have dropped the jailroot option because relative addons paths are now supported. The buildout can be moved anywhere and keeps on running.

To answer an issue raised in the original merge proposal: the python-executable option is useful in the case that the buildout is bootstrapped using a virtualenv that may not be available in the target location (jailroot or even another server, which is my current use case). No need to use this option when the buildout is bootstrapped using the unisolated system python or if the virtualenv remains available after relocation.

**Comment by agb80** [comment]
+1

PD: Thanks @StefanRijnhart  I have been waiting for this feature for long time.

**Comment by hbrunn** [comment]
@StefanRijnhart I adapted to current changes in #104, do you want to cherry-pick this or close this PR?

**Comment by StefanRijnhart** [comment]
Closing in favour of #104

**Pull request closed without merging**
