### PR TITLE
[IMP] Simplify travis

### PR DESCRIPTION
**Pull request by lmignon**
Simplify travis
Test building documentation with travis
PEP8

### CODE REVIEW

**Comment by lmignon** [comment]
@bwrsandman I've simplified travis according to your comment in #57 
@petrus-v I install sphinx just before building the doc

**Comment by bwrsandman** [comment]
Sphinx fails the tests?

**Comment by bwrsandman** [comment]
:+1:

**Comment by petrus-v** [comment]
:+1:

**Comment by lmignon** [comment]
@petrus-v @bwrsandman I'll fix the documentation and replace the line `pip install -e .[test]` by 'python setup.py test`before merging

**Comment by lmignon** [comment]
@petrus-v @bwrsandman This one is ready to merge if you agree with the last chanegs. I hav'nt replaced the command `pip install -e .[test]` since the replacement has side effect on travis.

**Comment by petrus-v** [comment]
Thanks again for investigations on Travis configuration

:+1:

**Comment by lmignon** [comment]
ping @bwrsandman Can I merge this one?

**Comment by bwrsandman** [comment]
It looks good to me

**Pull request merged**
