### PR TITLE
V8 env

### PR DESCRIPTION
**Pull request by bwrsandman**
Create an api Environment with cursor, user id and context of superuser
This allows the following syntax from the get-go:

    new_partner = self.env['res.partner'].create({'name': 'bwrsandman'})

The syntax is consistent with api decorated functions and the Odoo unittest framework

Depends on #27

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1:

Perhaps it would also be nice to have uid has an argument of open()

**Comment by petrus-v** [comment]
:+1:

**Comment by bwrsandman** [comment]
@sbidoul It could be, but for you, you can use `sudo`

**Comment by gracinet** [comment]
Ok, thank you Sandy, sorry to have been so slow at this.

**Pull request merged**
