### PR TITLE
Use svg badge to match others

### PR DESCRIPTION
**Pull request by bwrsandman**
Before:
 before

After:
 before

### CODE REVIEW

**Comment by lmignon** [comment]
:+1:

**Comment by lmignon** [comment]
coverage result seems wrong

**Comment by bwrsandman** [comment]
Indeed, it seems to take the lowest coverage: the __init__ files

**Comment by bwrsandman** [comment]
We could add `# pragma: no cover` at the import error

**Comment by bwrsandman** [comment]
Actually, never mind. It isn't covering the code, only the `__init__.py` files

**Pull request merged**
