### PR TITLE
Fix typo in example

### PR DESCRIPTION
**Pull request by bwrsandman**

### CODE REVIEW

**Comment by gracinet** [comment]
ah yes indeed, thanks.

**Comment by bwrsandman** [comment]
I am having trouble generating these scripts.

With underscore, I get an error but with dashes the script isn't created...

**Comment by gracinet** [comment]
Did you not forget to add 'sphinx' to the eggs ?

**Comment by bwrsandman** [comment]
It's there

**Comment by bwrsandman** [comment]
```cfg
[buildout]
parts =
        openerp

versions = versions
find-links = http://download.gna.org/pychart/

[openerp]
recipe = anybox.recipe.openerp[bzr]:server
eggs = sphinx
version = git https://github.com/odoo/odoo.git  ../../../odoo 7.0
addons = local ../addons

with_devtools = False
openerp_scripts =
    openerp_starter=start_openerp
    openerp_upgrader=upgrade_openerp
    sphinx-build=sphinx_build.py command-line-options=-d
    sphinx-apidoc=sphinx_apidoc.py command-line-options=-d
    sphinx-quickstart=sphinx_quickstart.py
interpreter_name=python_openerp

[versions]
```

Running `./bin/buildout install`

**Comment by gracinet** [comment]
I'm not sure if the '.py' does not go in the way. Here's one that works, from a real-life project:

```
eggs =
    soappy
    PyPDF
    nose
    coverage
    nose-cprof
    sphinx
    anybox.testing.openerp

options.load_language = fr_FR
options.language = fr_FR

openerp_scripts = nosetests=nosetests openerp-log-level=WARNING command-line-options=-d
                  sphinx-build=sphinx-build openerp-log-level=ERROR command-line-options=-d
                  sphinx-apidoc=sphinx-apidoc openerp-log-level=ERROR command-line-options=-d
                  sphinx-quickstart=sphinx-quickstart openerp-log-level=ERROR command-line-options=-d
```

**Comment by bwrsandman** [comment]
.py works, I tested in a new directory. I think there's something wrong with my environment.

**Pull request merged**
