### PR TITLE
Document how to use IPython/bpython with session

### LINKED ISSUE #12: python_odoo with ipython
@veloutin showed me this awesome patch he makes to python_odoo to use an ipython console to take advantage of its features.

Could this be officially added to the recipe?

```patch
--- bin/python_odoo	2014-07-25 15:11:16.467096106 -0400
+++ bin/python_odoo	2014-07-25 15:11:05.073762648 -0400
@@ -66,4 +66,9 @@
 
 if _interactive:
     del _interactive
+    try:
+        import IPython
+    except ImportError:
+        __import__("code").interact(banner="", local=globals())
+    else:
+        IPython.start_ipython(user_ns=globals())
-    __import__("code").interact(banner="", local=globals())
```

### PR DESCRIPTION
**Pull request by leorochael**
Closes #12.

### CODE REVIEW

**Comment by petrus-v** [comment]
@leorochael 

Thanks for the documentation. :+1: 

Don't worry about travis test as #49 isn't merge, yet!

**Comment by lmignon** [comment]
@leorochael thank you for the doc :+1:

**Comment by leorochael** [comment]
I've subscribed to #49. As soon as it's merged I'll rebase, if this PR wasn't merged yet.

**Comment by bwrsandman** [comment]
Thank you so much for your involvement @leorochael!
:+1:

**Comment by leorochael** [comment]
Do not merge yet, found typos.

**Comment by leorochael** [comment]
Better now. Feel free to merge.

**Pull request merged**
