### PR TITLE
[FIX] don't crash on <= v7

### PR DESCRIPTION
**Pull request by hbrunn**
this fixes a regression introduced by https://github.com/anybox/anybox.recipe.odoo/commit/bbd313b54d216eabc846102312c738c8917eea18, causing upgrade to fail on v7 installations

### CODE REVIEW

**Comment by gracinet** [comment]
Hum, thank you Holger, but anybox.recipe.odoo has never been meant to support v7.

We actually took the rename to Odoo as an opportunity to remove lots of old special conditions meant for <v8 cases (Babel, PIL, real ugly stuff like the patch for v5) and keep compat with older versions in anybox.recipe.openerp. 
So, normally you'd want to use that (and I intend also to backport to it some fixes that make sense for both after a.r.odoo's release)

I don't want to be harsh and refuse so simple a fix if you need it, but I'd like to recover later the ability to simplify the code afterwards (that includes these checks for the new API as well), so please try and use the other one when you can.

**Comment by hbrunn** [comment]
thanks for merging anyways! I was not even aware that .openerp is still maintained, will have a look there

**Comment by hbrunn** [comment]
PS: for the record: It works perfectly fine for v7 for the time being :-)

**Comment by gracinet** [comment]
I'm not surprised it actually works, I've not done that much removal of old stuff, and that was mostly scary stuff mean for <v7. Perhaps I should have been more violent at the time :-)

a.r.openerp is not very active, but we do use it on a few projects, it's there to stay

**Pull request merged**
